name: pocket_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.5.4
  cloud_firestore: ^6.6.0
  intl: ^0.20.2
  fl_chart: ^0.69.0
  pdf: ^3.11.1
  printing: ^5.13.4
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/pocket_tracker_logo.png
    - assets/images/pt_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pt_icon.png"
  min_sdk_android: 21